In [1]:
%%bash
pip install lark-parser




# APL Grammar 
( http://www.jsoftware.com/papers/APLDictionary1.htm )

APL has six grammatical elements:

1. 	**Nouns**, such as the *numbers* `3` and `5.6` , alphabetic characters or literals such as `+` and `A` and `a` . 
 
2. 	**Verbs**, such as `+` (addition) and `|` (magnitude) that act upon nouns to produce results that are also nouns. The nouns to which a particular verb applies are called its *arguments* (a word adopted in its sense of theme, or *subject*). A verb may have two distinct (but usually related) meanings according to whether it is applied to one argument (to its right) or two arguments (to its left and right). For example:
```apl
         2÷5                    ÷4
    .4                     .25
```
3. 	**Adverbs**, such as `/` , that act upon verbs or nouns. For example, `+/` is a (*derived*) verb called plus across that sums any list of numbers to which it is applied, and `×/` is a verb that yields the product across all elements of a list.

 When an adverb applies to a noun rather than to a verb (as in `1 0 2 /` to produce a “selection” verb so that `1 0 2 / 5 8 7` yields `5 7 7`) it might well be called an _adjective_. However, since such production of verbs from nouns is (in English) more commonly performed by a suffix rather than by an adjective (as in deify, reify, and nitrify), we will use the term _adverb_ for all cases. 
 
4. 	**Conjunctions**, such as `⍤` and `¨` , which apply to two arguments, as `⌽⍤⍉` (reverse and transpose). The arguments of a conjunction may be either verbs (as in the examples above) or nouns (as in `10¨⍟` , meaning base-ten logarithm). 
 
5. 	A **copula**, denoted by the arrow ← , and used to assign a name to a noun, verb, adverb, or conjunction. For example:
 ```apl
        area←4×8
        3+area
    35
        sum←+/
        sum 2 3 4
    9
 ```
 The arrow plays the same role as the copulas “is” and “are” in English; it is usually read as “is”, as in “area is four times eight” for `area←4×8` , and “(the verb) sum is plus across” for `sum←+/` . 

 A name assigned to a noun will be called a *pronoun*, and one assigned to a verb may be called a *proverb* (pronounced with a long o as in “pronoun” to distinguish it from the existing English word).

6.  **Punctuation**, provided by paired parentheses that specify the sequence of execution just as they do in elementary algebra. Sentences must appear on separate lines, and no punctuation is used to separate them.

# J Reference

How expressions get evaluated:
http://www.jsoftware.com/help/learning/91.htm
All the "parts of speech" reference:
http://www.jsoftware.com/help/dictionary/partsofspeech.htm

In [3]:
J_grammar = r"""
    ?start: expression
    
    pos_num:      NUMBER
    minus_num :   "_"pos_num
    ?signed_num:   pos_num|minus_num
    complex_num: signed_num"j"signed_num
    
    ?num : signed_num|complex_num  
    
    _WS : WS
    
    list: num (_WS num)* 
    
    ?verb: symbol
    ?symbol: "+"   -> plus
          |  "*"   -> times
          
    monad: symbol _WS* list
    dyad:  list   _WS* verb _WS* list
    
    expression: list|monad|dyad

    %import common.NUMBER
    %import common.WS
"""

http://code.jsoftware.com/wiki/User:Devon_McCormick/MinimalBeginningJ

<table class="wikitable">

    <tr>
        <td colspan="2" style="text-align: center;"> <b>Basics</b>
        </td>
        <td colspan="2" style="text-align: center;"> <b>Examples</b> (paste into J)
        </td></tr>
    <tr>
        <td>=. <a href="http://code.jsoftware.com/wiki/Vocabulary/eqdot" title="Vocabulary/eqdot">Is (local assignment)</a>
        </td>
        <td>=:  <a href="http://code.jsoftware.com/wiki/Vocabulary/eqco" title="Vocabulary/eqco">Is (global assignment)</a>
        </td>
        <td><tt>loc=. 1 2</tt>
        </td>
        <td><tt>GLO=: 'foo'</tt>
        </td></tr>
    <tr>
        <td>_ <a href="http://code.jsoftware.com/wiki/Vocabulary/under" title="Vocabulary/under">Negative Sign • Infinity</a>
        </td>
        <td>NB. <a href="http://code.jsoftware.com/wiki/Vocabulary/ncapbcapdot" title="Vocabulary/ncapbcapdot">Comment</a>
        </td>
        <td><tt>_3 = -3</tt>
        </td>
        <td><tt>NB. negative vs. negate</tt>
        </td></tr>
    <tr>
        <td>'string' <a rel="nofollow" class="external text" href="http://www.jsoftware.com/jwiki/Guides/General%20FAQ/Numbers%20and%20Character%20Representations#Character_to_Number_.28.22..29">Character string</a>
        </td>
        <td>
        </td>
        <td><tt>'' NB. Empty vector</tt>
        </td>
        <td><tt>'Hello, World!'</tt>
        </td></tr>
    <tr>
        <td colspan="4" style="text-align: center;"> <b>Arrays</b>
        </td></tr>
    <tr>
        <td> &#36; <a href="http://code.jsoftware.com/wiki/Vocabulary/dollar" title="Vocabulary/dollar">Shape Of • Reshape</a>
        </td>
        <td># <a href="http://code.jsoftware.com/wiki/Vocabulary/number" title="Vocabulary/number">Tally • Copy</a>
        </td>
        <td><tt>2 2 4 &#36; 1 2 11 22</tt>
        </td>
        <td><tt>1 2 3 # 1 2 3</tt>
        </td></tr>
    <tr>
        <td>, <a href="http://code.jsoftware.com/wiki/Vocabulary/comma" title="Vocabulary/comma">Ravel • Append</a>
        </td>
        <td>; <a href="http://code.jsoftware.com/wiki/Vocabulary/semi" title="Vocabulary/semi">Raze / Link</a>
        </td>
        <td><tt>, 2 2$99</tt>
        </td>
        <td><tt>23&#160;; 'skidoo'</tt>
        </td></tr>
    <tr>
        <td>{. <a href="http://code.jsoftware.com/wiki/Vocabulary/curlylfdot#dyadic" title="Vocabulary/curlylfdot">Take</a>
        </td>
        <td> }. <a href="http://code.jsoftware.com/wiki/Vocabulary/curlyrtdot#dyadic" title="Vocabulary/curlyrtdot">Drop</a>
        </td>
        <td><tt>3 {. 'foot'</tt>
        </td>
        <td><tt>2 }. 1 2 3 4</tt>
        </td></tr>
    <tr>
        <td>/ <a href="http://code.jsoftware.com/wiki/Vocabulary/slash" title="Vocabulary/slash">Insert • Table</a>
        </td>
        <td>i. <a href="http://code.jsoftware.com/wiki/Vocabulary/idot" title="Vocabulary/idot">Integers • Index of</a>
        </td>
        <td><tt>+ / 1 10 100</tt>
        </td>
        <td><tt>i. 10</tt>
        </td>
        <td><tt>'foo' i. 'o'</tt>
        </td></tr>
    <tr>
        <td colspan="4" style="text-align: center;"> <b>Math</b>
        </td></tr>
    <tr>
        <td><tt>+</tt> <a href="http://code.jsoftware.com/wiki/Vocabulary/plus#dyadic" title="Vocabulary/plus">Conjugate • Plus</a>
        </td>
        <td>* <a href="http://code.jsoftware.com/wiki/Vocabulary/star#dyadic" title="Vocabulary/star">Signum • Times</a>
        </td>
        <td><tt>2 + 3 30</tt>
        </td>
        <td><tt>3 30 * 2</tt>
        </td></tr>
    <tr>
        <td> - <a href="http://code.jsoftware.com/wiki/Vocabulary/minus" title="Vocabulary/minus">Negate • Subtract</a>
        </td>
        <td>% <a href="http://code.jsoftware.com/wiki/Vocabulary/percent#dyadic" title="Vocabulary/percent">Reciprocal • Divide</a>
        </td>
        <td><tt>1 10 - 5 6</tt>
        </td>
        <td><tt>2 3 5&#160;% 3 4 6</tt>
        </td></tr>
    <tr>
        <td><tt>^</tt> <a href="http://code.jsoftware.com/wiki/Vocabulary/hat#dyadic" title="Vocabulary/hat">Exponential • Power</a>
        </td>
        <td><tt>^.</tt> <a href="http://code.jsoftware.com/wiki/Vocabulary/hatdot" title="Vocabulary/hatdot">Natural Log • Log</a>
        </td>
        <td><tt>2 ^ i.17</tt>
        </td>
        <td><tt>2 10 ^. 4 100</tt>
        </td>
        <td><tt>&#160;^. 2.71828</tt>
        </td></tr>
    <tr>
        <td><tt>&lt;.</tt> <a href="http://code.jsoftware.com/wiki/Vocabulary/ltdot" title="Vocabulary/ltdot">Floor • Minimum</a>
        </td>
        <td><tt>&gt;.</tt> <a href="http://code.jsoftware.com/wiki/Vocabulary/gtdot" title="Vocabulary/gtdot">Ceiling • Maximum</a>
        </td>
        <td><tt>2 3 4 &lt;. 99 1 2</tt>
        </td>
        <td><tt>&#160;&gt;. 1.1 0.5 1.9</tt>
        </td></tr></table>

In [32]:
from lark import Transformer, Lark
import numpy as np

# verbs have form name:(monad,dyad)
verbs = { 
    "plus"  : ("np.conj","np.add",),
    "times" : ("np.sign","np.multiply")
}

class run_J(Transformer):
    def expression(_,e):
        return e
    
    def pos_num(self, n1):
        # n1:  [Token(NUMBER, '4')]
        n,=n1
        return np.float(n)
    def complex_num(self, z):
        j = np.complex(1j)
        a,b=z
        #print("a+bi: ",z)
        return a+b*j
    def minus_num(self,n1):
        #print("n1: ",n1)
        n,=n1
        return -n
    
    def list(self,l):
        return "np.array(" + str(l) + ")"

    def dyad(self,a_op_b):
        a,op,b=a_op_b
        #print("a op b:",a,op,b)
        f = verbs[op][1]
        return "{f}({a},{b})".format(f=f,a=a,b=b)
    def monad(self,op_a):
        op,a=op_a
        print("op a:",op,a)
        f = verbs[op][0]
        return "{f}({a})".format(f=f,a=a)
    
    times = lambda self,_: "times"
    plus = lambda self,_: "plus"
               
        
    '''
    def __getattr__(self, name):
        def _missing(*args, **kwargs):
            # assume anything missing is literal
            return name
        return _missing
    '''

parser = Lark(J_grammar)
def parse_and_run_J(code):  
    tree = parser.parse(code)
    #print(tree,tree.pretty())
    return (run_J().transform(tree))[0]

def eval_J(code):
    return eval(parse_and_run_J(code))
    

In [33]:
test_string = "4 3  6 * 2  _3 4" 
parse_and_run_J(test_string)
eval_J(test_string)

array([  8.,  -9.,  24.])

In [6]:
test_string = "+3 4j5 _6 0.01 3j2"
runJ(test_string)

array([ 3.00-0.j,  4.00-5.j, -6.00-0.j,  0.01-0.j,  3.00-2.j])

In [24]:
np.multiply(np.array([4.0, 3.0, 6.0]),np.array([2.0, -3.0, 4.0]))

array([  8.,  -9.,  24.])

In [25]:
test_string = "+3 4j5 _6 0.01 3j2"
parse_and_run_J(test_string)

Tree(expression, [Tree(monad, [Tree(plus, []), Tree(list, [Tree(pos_num, [Token(NUMBER, '3')]), Tree(complex_num, [Tree(pos_num, [Token(NUMBER, '4')]), Tree(pos_num, [Token(NUMBER, '5')])]), Tree(minus_num, [Tree(pos_num, [Token(NUMBER, '6')])]), Tree(pos_num, [Token(NUMBER, '0.01')]), Tree(complex_num, [Tree(pos_num, [Token(NUMBER, '3')]), Tree(pos_num, [Token(NUMBER, '2')])])])])]) expression
  monad
    plus
    list
      pos_num	3
      complex_num
        pos_num	4
        pos_num	5
      minus_num
        pos_num	6
      pos_num	0.01
      complex_num
        pos_num	3
        pos_num	2

op a: plus np.array([3.0, (4+5j), -6.0, 0.01, (3+2j)])


'np.conj(np.array([3.0, (4+5j), -6.0, 0.01, (3+2j)]))'

In [26]:
np.conj(np.array([3.0, (4+5j), -6.0, 0.01, (3+2j)]))

array([ 3.00-0.j,  4.00-5.j, -6.00-0.j,  0.01-0.j,  3.00-2.j])